<?php aint\html\head_title($title = app\translate('My Albums')) ?>
<h1><?= htmlspecialchars($title) ?></h1>
<p>
    <a href="<?= app\uri('albums\add_action') ?>">Add new album</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Controls</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($albums as $album) : ?>
    <tr>
        <td><?= htmlspecialchars($album['title']) ?></td>
        <td><?= htmlspecialchars($album['artist']) ?></td>
        <td>
            <a href="<?= app\uri('albums\edit_action', ['id' => $album['id']]) ?>">Edit</a> |
            <a href="<?= app\uri('albums\delete_action', ['id' => $album['id']]) ?>">Delete</a>
        </td>
    </tr>
        <?php endforeach ?>
    </tbody>
</table>
