<?php aint\html\head_title($title = t('System')) ?>
<h1><?= h($title) ?></h1>

<h2><?= t('Constants') ?></h2>
<table class="table">
<?php foreach ($constants as $name => $value): ?>
  <tr>
    <td><?= $name ?></td>
    <td><?= $value ?></td>
  </tr>
<?php endforeach ?>
</table>

<h2><?= t('Structs') ?></h2>
<table class="table">
<?php foreach ($classes as $class): ?>
  <tr>
    <td><?= $class ?></td>
  </tr>
<?php endforeach ?>
</table>

<h2><?= t('Functions') ?></h2>
<table class="table">
<?php foreach ($functions as $function): ?>
  <tr>
    <td><?= $function ?></td>
  </tr>
<?php endforeach ?>
</table>
