<form action="<?= $action ?>" method="post" class="form-horizontal well">
  <fieldset>
    <div class="control-group">
      <label class="control-label" for="title"><?= t('Title') ?></label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="title" name="title" value="<?= h($album['title']) ?>" autofocus />
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="artist"><?= t('Artist') ?></label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="artist" name="artist" value="<?= h($album['artist']) ?>" />
      </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary"><?= t('Save') ?></button>
      &nbsp; <a href="<?= url('albums\index_action') ?>"><?= t('Cancel') ?></a>
    </div>
  </fieldset>
</form>
